import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ChartColumnBigIcon } from "lucide-react";
import Link from "next/link";
import { Suspense } from "react";
import { ClerkProvider } from "@clerk/nextjs";
import NavAuth from "@/components/NavAuth";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <ClerkProvider signInUrl="/sign-in" signUpUrl="/sign-up">
      <html lang="en" className={`${poppins.variable}  h-full antialiased`}>
        <body className="min-h-full flex flex-col">
          <nav className="bg-primary px-4 text-white h-16 flex items-center justify-between gap-2 sm:h-20 sm:px-6">
            <Link
              href="/"
              className="font-bold text-xl flex gap-1 items-center sm:text-2xl"
            >
              <ChartColumnBigIcon className="text-lime-500" /> NextCash
            </Link>
            <header className="flex justify-end items-center gap-1 sm:gap-4">
              <Suspense
                fallback={<div className="size-7 rounded-full bg-white/20" />}
              >
                <NavAuth />
              </Suspense>
            </header>
          </nav>
          {children}
          <Toaster theme="light" closeButton />
        </body>
      </html>
    </ClerkProvider>
  );
}
