import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ChartColumnBigIcon } from "lucide-react";
import Link from "next/link";
import { ClerkProvider, Show, SignInButton, SignUpButton } from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import { Toaster } from "@/components/ui/sonner";
import UserDropdown from "@/components/UserDropdown";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <ClerkProvider signInUrl="/sign-in" signUpUrl="/sign-up">
      <html lang="en" className={`${poppins.variable}  h-full antialiased`}>
        <body className="min-h-full flex flex-col">
          <nav className="bg-primary px-4 text-white h-16 flex items-center justify-between gap-2 sm:h-20 sm:px-6">
            <Link
              href="/"
              className="font-bold text-xl flex gap-1 items-center sm:text-2xl"
            >
              <ChartColumnBigIcon className="text-lime-500" /> NextCash
            </Link>
            <header className="flex justify-end items-center gap-1 sm:gap-4">
              <Show when="signed-out">
                <SignInButton>
                  <Button variant="link" className="text-white">
                    Sign In
                  </Button>
                </SignInButton>
                <SignUpButton>
                  <Button variant="link" className="text-white">
                    Sign Up
                  </Button>
                </SignUpButton>
              </Show>
              <Show when="signed-in">
                <UserDropdown />
              </Show>
            </header>
          </nav>
          {children}
          <Toaster theme="light" closeButton />
        </body>
      </html>
    </ClerkProvider>
  );
}
